DROP TABLE IF EXISTS DROITS_DE_MENU, ELEMENTS_DE_MENU, MENUS, DROITS_DE_GROUPES, DROITS, MOTS_DE_PASSE_UTILISATEURS, UTILISATEURS, GROUPES CASCADE;


CREATE TABLE GROUPES (
  Id_Groupe SERIAL PRIMARY KEY,
  Libelle_Groupe VARCHAR(255)
);

CREATE TABLE UTILISATEURS (
  Id_User SERIAL PRIMARY KEY
  Nom VARCHAR(255),
  Prenom VARCHAR(255),
  email VARCHAR(255),
  Password VARCHAR(255),
  Date_Creation TIMESTAMP,
  Id_Groupe INTEGER REFERENCES GROUPES(Id_groupe)
);

CREATE TABLE MOTS_DE_PASSE_UTILISATEURS (
  Id_mdp SERIAL PRIMARY KEY,
  Id_User INTEGER REFERENCES UTILISATEURS(Id_User),
  Date_Created TIMESTAMP,
  Password VARCHAR(255)
);

CREATE TABLE DROITS (
  Id_droit SERIAL PRIMARY KEY,
  Libbelle_droit VARCHAR(255)
);

CREATE TABLE DROITS_DE_GROUPES (
  Id SERIAL PRIMARY KEY,
  Id_Groupe INTEGER REFERENCES GROUPES(Id_Groupe),
  Id_droit INTEGER REFERENCES DROITS(Id_droit)
);

CREATE TABLE MENUS (
  Id_Menu SERIAL PRIMARY KEY,
  Nom_Menu VARCHAR(255) NOT NULL,
  Ordre_Affichage INTEGER NOT NULL
);

CREATE TABLE ELEMENTS_DE_MENU (
  Id_element SERIAL PRIMARY KEY,
  Nom_Menu VARCHAR(255) NOT NULL,
  Ordre_Affichage INTEGER NOT NULL,
  Lien VARCHAR(255),
  Id_Menu INTEGER REFERENCES MENUS(Id_Menu) ON DELETE CASCADE
);

CREATE TABLE DROITS_DE_MENU (
  Id SERIAL PRIMARY KEY,
  Id_Groupe INTEGER REFERENCES GROUPES(Id_Groupe) ON DELETE CASCADE,
  Id_Menu INTEGER REFERENCES MENUS(Id_Menu) ON DELETE CASCADE,
  Id_element INTEGER REFERENCES ELEMENTS_DE_MENU(Id_element) ON DELETE CASCADE
);