DROP TABLE IF EXISTS DROITS_DE_MENU CASCADE;
DROP TABLE IF EXISTS ELEMENTS_DE_MENU CASCADE;
DROP TABLE IF EXISTS MENUS CASCADE;
DROP TABLE IF EXISTS DROITS_DE_GROUPES CASCADE;
DROP TABLE IF EXISTS DROITS CASCADE;
DROP TABLE IF EXISTS MOTS_DE_PASSE_UTILISATEURS CASCADE;
DROP TABLE IF EXISTS UTILISATEURS CASCADE;
DROP TABLE IF EXISTS GROUPES CASCADE;

CREATE TABLE GROUPES (
  Id SERIAL PRIMARY KEY,
  Groupe VARCHAR(255)
);

CREATE TABLE UTILISATEURS (
    first_Name VARCHAR(255),
    Last_Name VARCHAR(255),
    Date_Created TIMESTAMP,
    Group_Id INTEGER REFERENCES GROUPES(id)
);

ALTER TABLE UTILISATEURS ADD COLUMN PASSWORD VARCHAR(255);
ALTER TABLE UTILISATEURS ADD COLUMN User_Id SERIAL PRIMARY KEY;

CREATE TABLE MOTS_DE_PASSE_UTILISATEURS (
  id SERIAL PRIMARY KEY,
  User_Id INTEGER REFERENCES UTILISATEURS(User_Id),
  Date_Created TIMESTAMP,
  Password VARCHAR(255)
);

CREATE TABLE DROITS (
  Id SERIAL PRIMARY KEY,
    Right_Name VARCHAR(255)
);

CREATE TABLE DROITS_DE_GROUPES (
  Id SERIAL PRIMARY KEY,
  Group_Id INTEGER REFERENCES GROUPES(Id),
  Right_Id INTEGER REFERENCES DROITS(Id)
);

CREATE TABLE MENUS (
    Id SERIAL PRIMARY KEY,
  Nom_menu VARCHAR(255) NOT NULL,
  Ordre_Affichage INTEGER NOT NULL
);

CREATE TABLE ELEMENTS_DE_MENU (
    Id SERIAL PRIMARY KEY,
  Nom_Menu VARCHAR(255) NOT NULL,
  Ordre_Affichage INTEGER NOT NULL,
  Lien VARCHAR(255),
    Menu_Id INTEGER REFERENCES MENUS(id) ON DELETE CASCADE
);

CREATE TABLE DROITS_DE_MENU (
    Id SERIAL PRIMARY KEY,
  Group_Id INTEGER REFERENCES GROUPES(id) ON DELETE CASCADE,
    Menu_Id INTEGER REFERENCES MENUS(id) ON DELETE CASCADE,
  Element_Id INTEGER REFERENCES ELEMENTS_DE_MENU(id) ON DELETE CASCADE
)

